name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: build-artifacts
          path: tpl-weltspiegel.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: tpl-weltspiegel.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
